[project]
name = "automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "numpy>=2.1.2",
    "pandas>=2.2.3",
    "xlogit",
    "requests<3",
]
